"""
swagger에 출력될 comments
"""

tags_metadata = [
    {"name": "인증 - 세션", "description": "/auth 도메인 묶음"},
    {"name": "인증 - sns 로그인 연동", "description": "/auth 도메인 묶음"},
    {"name": "인증 - 기타", "description": "/auth 도메인 묶음"},
    {"name": "작품 - 작품 노출관리", "description": "/products 도메인 묶음"},
    {"name": "작품 - 전체 목록(유,무료)", "description": "/products 도메인 묶음"},
    {"name": "작품 - 에피소드 목록 조회", "description": "/products 도메인 묶음"},
    {
        "name": "작품 - 상세정보 그룹핑(작품, 공지, 평가)",
        "description": "/products 도메인 묶음",
    },
    {"name": "작품 - 작가의 다른 작품 조회", "description": "/products 도메인 묶음"},
    {"name": "작품 - 작가의 작품 평가 조회", "description": "/products 도메인 묶음"},
    {"name": "작품 - 평가 조회", "description": "/products 도메인 묶음"},
    {"name": "작품 - 추천작품 노출관리", "description": "/products 도메인 묶음"},
    {"name": "작품 - 추천작품 조회", "description": "/products 도메인 묶음"},
    {"name": "작품 - 작품 관리", "description": "/products 도메인 묶음"},
    {"name": "작품 - 작품 공지", "description": "/products 도메인 묶음"},
    {"name": "작품 - 댓글", "description": "/products 도메인 묶음"},
    {"name": "작품 - 북마크", "description": "/products 도메인 묶음"},
    {"name": "회차 - 회차 관리", "description": "/episodes 도메인 묶음"},
    {"name": "회차 - 뷰어", "description": "/episodes 도메인 묶음"},
    {"name": "회차 - 좋아요", "description": "/episodes 도메인 묶음"},
    {"name": "배너 - 조회", "description": "/banners 도메인 묶음"},
    {"name": "유저 - 메인페이지", "description": "/user 도메인 묶음"},
    {"name": "유저 - 홈", "description": "/user 도메인 묶음"},
    {"name": "유저 - CP/편집자 신청", "description": "/user/apply-role 도메인 묶음"},
    {"name": "유저 - 프로필", "description": "/user 도메인 묶음"},
    {"name": "유저 - 캐시", "description": "/user 도메인 묶음"},
    {"name": "유저 - 댓글", "description": "/user 도메인 묶음"},
    {"name": "유저 - 알림", "description": "/user 도메인 묶음"},
    {"name": "주문", "description": "/orders 도메인 묶음"},
    {"name": "결제", "description": "/payments 도메인 묶음"},
    {"name": "메시지", "description": "/messages 도메인 묶음"},
    {"name": "알림", "description": "/alarms 도메인 묶음"},
    {"name": "선물함", "description": "/gifts 도메인 묶음"},
    {"name": "이벤트", "description": "/events 도메인 묶음"},
    {"name": "퀘스트", "description": "/quests 도메인 묶음"},
    {"name": "통합검색", "description": "/search 도메인 묶음"},
    {"name": "고객지원", "description": "/support 도메인 묶음"},
    {"name": "공지사항", "description": "/notices 도메인 묶음"},
    {"name": "CMS - 관리자", "description": "/admins 도메인 묶음"},
    {"name": "CMS - 회원", "description": "/admins/users 도메인 묶음"},
    {"name": "CMS - 자격 신청", "description": "/admins/apply-role 도메인 묶음"},
    {"name": "CMS - 뱃지", "description": "/admins/badge 도메인 묶음"},
    {"name": "CMS - 승급 신청", "description": "/admins/apply-rank-up 도메인 묶음"},
    {
        "name": "CMS - 리뷰/댓글/공지",
        "description": "/admins/reviews-comments-notices 도메인 묶음",
    },
    {"name": "CMS - 리뷰", "description": "/admins/reviews 도메인 묶음"},
    {"name": "CMS - 댓글", "description": "/admins/comments 도메인 묶음"},
    {"name": "CMS - 공지", "description": "/admins/notices 도메인 묶음"},
    {"name": "CMS - 테마 키워드", "description": "/admins/keywords 도메인 묶음"},
    {
        "name": "CMS - 출판사 프로모션",
        "description": "/admins/publisher-promotion 도메인 묶음",
    },
    {
        "name": "CMS - 알고리즘 추천구좌",
        "description": "/admins/algorithm-recommend 도메인 묶음",
    },
    {
        "name": "CMS - 직접 추천구좌",
        "description": "/admins/direct-recommend 도메인 묶음",
    },
    {
        "name": "CMS - 직접 프로모션",
        "description": "/admins/direct-promotion 도메인 묶음",
    },
    {
        "name": "CMS - 신청 프로모션",
        "description": "/admins/applied-promotion 도메인 묶음",
    },
    {"name": "CMS - 선물함", "description": "/admins/user-giftbook 도메인 묶음"},
    {"name": "CMS - 메시지", "description": "/admins/messages 도메인 묶음"},
    {"name": "CMS - 푸시 메시지", "description": "/admins/push 도메인 묶음"},
    {"name": "CMS - 퀘스트", "description": "/admins/quests 도메인 묶음"},
    {"name": "CMS - 이벤트", "description": "/admins/events 도메인 묶음"},
    {"name": "CMS - 배너", "description": "/admins/banners 도메인 묶음"},
    {"name": "CMS - 팝업", "description": "/admins/popup 도메인 묶음"},
    {"name": "CMS - FAQ", "description": "/admins/faq 도메인 묶음"},
    {"name": "CMS - 비율 조정", "description": "/admins/common-rate 도메인 묶음"},
    {"name": "CMS - 작품", "description": "/admins/products 도메인 묶음"},
    {
        "name": "CMS - 공지사항(사이트 공지)",
        "description": "/admins/general-notices 도메인 묶음",
    },
    {"name": "파트너", "description": "/partners 도메인 묶음"},
    {"name": "파트너 - 작품", "description": "/partners/products 도메인 묶음"},
    {
        "name": "파트너 - 작품별 통계",
        "description": "/partners/product-statistics 도메인 묶음",
    },
    {
        "name": "파트너 - 회차별 통계",
        "description": "/partners/product-episode-statistics 도메인 묶음",
    },
    {
        "name": "파트너 - 장바구니 분석",
        "description": "/partners/cart-analysis 도메인 묶음",
    },
    {
        "name": "파트너 - 시간별 유입",
        "description": "/partners/hourly-inflow 도메인 묶음",
    },
    {
        "name": "파트너 - 작품별 월매출",
        "description": "/partners/monthly-sales-by-product 도메인 묶음",
    },
    {
        "name": "파트너 - 회차별 매출",
        "description": "/partners/sales-by-episode 도메인 묶음",
    },
    {
        "name": "파트너 - 일별 이용권 상세",
        "description": "/partners/daily-ticket 도메인 묶음",
    },
    {
        "name": "파트너 - 월별 정산",
        "description": "/partners/monthly-settlement 도메인 묶음",
    },
    {
        "name": "파트너 - 선계약금 차감 조회",
        "description": "/partners/product-contract-offer-deduction 도메인 묶음",
    },
    {
        "name": "파트너 - 후원 내역",
        "description": "/partners/sponsorship-recodes 도메인 묶음",
    },
    {
        "name": "파트너 - 기타 수익 내역",
        "description": "/partners/income-recodes 도메인 묶음",
    },
    {
        "name": "파트너 - 후원 및 기타 정산",
        "description": "/partners/income-settlement 도메인 묶음",
    },
    {
        "name": "파트너 - 발굴 통계",
        "description": "/partners/product-discovery-statistics 도메인 묶음",
    },
    {"name": "스토리지", "description": "/storages 도메인 묶음"},
]
